CREATE TABLE CONFIGURATION_PARAMETERS 
(
  KEY VARCHAR2(100),
   VALUE VARCHAR2(100) 
);

CREATE SEQUENCE JOB_ID_SEQUENCE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 MINVALUE 1;

INSERT INTO "FRACTALS_BATCH"."CONFIGURATION_PARAMETERS" (KEY, VALUE) VALUES ('COMMIT_SIZE', '10');
INSERT INTO "FRACTALS_BATCH"."CONFIGURATION_PARAMETERS" (KEY, VALUE) VALUES ('LANDING_DIRECTORY', '/home/fractals/batch/landing');
INSERT INTO "FRACTALS_BATCH"."CONFIGURATION_PARAMETERS" (KEY, VALUE) VALUES ('PROCESSING_DIRECTORY', '/home/fractals/batch/processing')
INSERT INTO "FRACTALS_BATCH"."CONFIGURATION_PARAMETERS" (KEY, VALUE) VALUES ('SUCCESS_DIRECTORY', '/home/fractals/batch/success');
INSERT INTO "FRACTALS_BATCH"."CONFIGURATION_PARAMETERS" (KEY, VALUE) VALUES ('ERROR_DIRECTORY', '/home/fractals/batch/errors');

commit;
